spring:
    application:
        name: mobile-gallery
    config:
        activate:
            on-profile: development, default
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: none
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 15MB
            
    datasource:
        url: "jdbc:mysql://localhost:3306/gallery"
        username: "gallery"
        password: "gallery"
        driver-class-name: "com.mysql.cj.jdbc.Driver"
management:
    endpoints:
        web:
            exposure:
                include: [health, mappings, env]
server:
  tomcat:
    max-http-form-post-size: 10485760 # 10MB
    max-swallow-size: -1
logging:
  level:
    root: INFO
    org:
        hibernate:
            orm:
                jdbc:
                    bind: TRACE
        springframework:
            security: DEBUG