spring:
    application:
        name: mobile-gallery
    config:
        activate:
            on-profile: development, default
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
    datasource:
        url: "jdbc:mysql://localhost:3306/gallery"
        username: "gallery"
        password: "gallery"
        driver-class-name: "com.mysql.cj.jdbc.Driver"
management:
    endpoints:
        web:
            exposure:
                include: [health, mappings]